forensik/account/urls.py
# account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("signup/", views.registerpage, name='signup'),
]

forensik/case/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "case"


urlpatterns = [
    path("", views.MapView.as_view(), name='map'),
    path("analyse", views.analyze_data, name='analyze'),
    path("image_import", views.get_device_folder, name='image_import')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

forensik/urls.py
""" forensik URL Configuration"""

from django.contrib import admin
from django.urls import path, include
from forensik.case import views

#Customizing "Django Admin Page" for our WebApp
admin.site.site_header = 'ForensicView'
admin.site.index_title = 'Case Manager'
admin.site.site_title = 'ForensicView Case Manager'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('forensik.account.urls', namespace='account')),
    path("", include('forensik.case.urls'))
]

data/templates/pages/accounts_base.html
{% extends 'pages/../pages/base_site.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon-32x32.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body id="custom_body">
<div class="form-group" style="margin: 5% 30% 0 30%">
    <div id="rcorners1" style="padding: 20px">
        <h2 style="text-align: center">{{ title }}</h2>
        <form method="POST" action="">
            {% block account_form %}
            {% endblock %}
            </form>
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <p style="color: green">{{ message }}</p>
                {% endif %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p style="color: darkred">{{ message }}</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

data/templates/pages/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
     <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon-32x32.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'case:map' %}">Forensik</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                                <li class="nav-item">
                <a class="nav-link" href="{% url 'account:signup' %}">Registrierung</a>
                         </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://localhost:8000/admin">Admin</a>
                    </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'case:map' %}">Karte</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'case:image_import' %}">Bild-Import</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'case:analyze' %}">Analyse</a>
            </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
        {% block content %}

        {% endblock %}
</body>
</html>